version: '3.4'

services:
  api:
    container_name: bookshelf-api
    build: .
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - mongodb
      - seq
      - prometheus

  seq:
    container_name: bookshelf-seq
    image: datalust/seq
    ports:
      - "8001:80"
    environment:
      ACCEPT_EULA: Y
      
  prometheus:
    container_name: bookshelf-prometheus
    image: prom/prometheus
    ports:
      - "8002:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  mongodb:
    container_name: bookshelf-mongo
    image: mongo
    restart: always
    volumes:
      - /.mongo-int/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_DATABASE: BookShelfDb